---
title: "staRVe-tour"
output:
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{staRVe-tour}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---





# Introduction


```r
set.seed(4326)
library(staRVe)
```

The staRVe package implements a spatio-temporal GLMM for analyzing discrete-time, continuous-space data.
Throughout this vignette we will refer to the time unit as year/yearly, although any other regular unit (daily, monthly, etc.) can be used.
Functionality include maximum likelihood inference, model-based spatial interpolation and forecasting and hindcasting, and simulations.
The sf and raster packages are tightly integrated into the staRVe package, allowing users to easily incorporate the staRVe package into their existing workflows.

The spatio-temporal GLMM is structured as a hierarchical model with 3 levels:

1. an observation equation describing the response distribution and covariate effects
2. a first level of spatio-temporal random effects describing the value of an unobserved spatio-temporal process, and
3. a second level of temporal random effects describing how the spatial surface changes as a whole from year to year.






# Data

The staRVe package expects data to be a sf data.frame with point geometries.
See the sf package.
The point geometries can have any valid geographic coordinate reference system, projected or unprojected, latitude/longitude or eastings/northings, or have no coordinate reference system (if appropriate).
In addition to the geometry column the sf data.frame should also include a response variable, the time index of the observation, and optionally any covariates desired.
The bird_survey dataset included in the staRVe package is an example of the necessary data format.


```r
data(bird_survey)
bird_survey
#> Simple feature collection with 783 features and 2 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: -95.23445 ymin: 36.11935 xmax: -89.2478 ymax: 40.47128
#> Geodetic CRS:  WGS 84
#> First 10 features:
#>    cnt year                       geom
#> 1    4 1994 POINT (-89.24779 36.82526)
#> 2    2 1994 POINT (-90.74799 36.59369)
#> 3    8 1994 POINT (-91.68653 36.86373)
#> 4    6 1994  POINT (-93.9101 36.66086)
#> 5   15 1994 POINT (-94.23886 36.56423)
#> 6    2 1994 POINT (-89.52656 37.30663)
#> 7   17 1994 POINT (-90.30749 37.25986)
#> 8    7 1994 POINT (-91.55293 37.37596)
#> 9   13 1994 POINT (-91.42393 37.90398)
#> 10  10 1994   POINT (-92.0354 37.7511)
```

The 'bird_survey' data holds the results of a yearly survey of Carolina wren in the state of Missouri, USA.
The number of individual birds encountered is stored in the 'cnt' column.
The year that each observation was taken in stored in the 'year' column.
The location of each observation, taken as the centroid of transect, is given in the 'geom' column.
We'll work with a smaller subset of the data in the vignette.


```r
bird_survey<- subset(bird_survey,year >= 2005)
```


## Creating and fitting a model

The 'prepare_staRVe_model' function uses a supplied sf data.frame to create a 'staRVe_model' object.


```r
bird_model<- prepare_staRVe_model(
  cnt ~ time(year),
  data = bird_survey,
  distribution = "poisson"
)
```

The first argument supplied to 'prepare_staRVe_model' is a formula, similar those used in calls to 'lm' or 'glm'.
Formulae used in this package can include a number of terms with a special syntax, described more thoroughly in section [Formula syntax].
The response distribution must also be specified, defaulting to a Gaussian distribution.
The available response distributions are described in section [Response distribution] and can also be viewed in your R session with the command 'get_staRVe_distributions("distribution")'.
Optional arguments for prepare_staRVe_model are described in the help file for the function.

The new staRVe_model object is shown below.


```r
bird_model
#> 
#> An object of class "staRVe_parameters"
#> Slot "covariance_function":
#> [1] "exponential"
#> 
#> Slot "spatial_parameters":
#> $cnt
#>       par se fixed
#> sd    0.0  0 FALSE
#> range 0.0  0 FALSE
#> nu    0.5  0  TRUE
#> 
#> 
#> Slot "time_parameters":
#> $cnt
#>     par se fixed
#> mu    0 NA FALSE
#> ar1   0 NA FALSE
#> sd    0 NA FALSE
#> 
#> 
#> Slot "response_distribution":
#> [1] "poisson"
#> 
#> Slot "response_parameters":
#> $cnt
#> [1] par   se    fixed
#> <0 rows> (or 0-length row.names)
#> 
#> 
#> Slot "link_function":
#> [1] "log"
#> 
#> Slot "fixed_effects":
#> $cnt
#> [1] par   se    fixed
#> <0 rows> (or 0-length row.names)
#> 
#> 
#> 
#> Data
#> Simple feature collection with 404 features and 3 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: -95.23445 ymin: 36.11935 xmax: -89.2478 ymax: 40.47128
#> Geodetic CRS:  WGS 84
#> First 10 features:
#>     cnt year graph_idx                       geom
#> 422   1 2005        63 POINT (-95.23445 40.46577)
#> 417   7 2005        62 POINT (-95.03312 40.02546)
#> 402   5 2005        59 POINT (-94.66548 39.65398)
#> 415   7 2005        58 POINT (-94.50103 39.39702)
#> 416   3 2005        57 POINT (-94.14222 40.10026)
#> 392   3 2005        29   POINT (-94.1192 37.1404)
#> 420   4 2005        43 POINT (-94.10504 38.66985)
#> 384  11 2005        37  POINT (-93.9101 36.66086)
#> 391   7 2005        26 POINT (-93.85185 37.77059)
#> 397   2 2005        24 POINT (-93.84015 38.19498)
```


```r
spatial_parameters(bird_model)$cnt["range","par"]<- 80
spatial_parameters(bird_model)$cnt["range","fixed"]<- TRUE
```

The individual components of a 'staRVe_model" object are explained in the following sections.
For now, note the columns labelled 'par' in the 'time_parameters', 'spatial_parameters', 'response_parameters', and 'fixed_effects' slots (the latter two of which have 0 rows in this particular model).
These are the parameter values for the model.
The 'staRVe_fit' function finds the maximum likelihood (ML) estimates of these parameters.
The parameter values in the staRVe_model object will be the starting values used when finding the ML estimate.
Details for changing these values is given in section [Modifying a staRVe model].


```r
bird_model<- staRVe_fit(
  bird_model,
  silent=T
)
```

The output of the 'staRVe_fit' function is a 'staRVe_model_fit' object.


```r
bird_model
#> 
#> [1] "relative convergence (4)"
#> 
#> An object of class "staRVe_parameters"
#> Slot "covariance_function":
#> [1] "exponential"
#> 
#> Slot "spatial_parameters":
#> $cnt
#>               par          se fixed
#> sd     0.05213431 0.003913888 FALSE
#> range 80.00000000 0.000000000  TRUE
#> nu     0.50000000 0.000000000  TRUE
#> 
#> 
#> Slot "time_parameters":
#> $cnt
#>           par         se fixed
#> mu  2.0066592 0.36396113 FALSE
#> ar1 0.9235859 0.03168324 FALSE
#> sd  0.1462888 0.07689308 FALSE
#> 
#> 
#> Slot "response_distribution":
#> [1] "poisson"
#> 
#> Slot "response_parameters":
#> $cnt
#> [1] par   se    fixed
#> <0 rows> (or 0-length row.names)
#> 
#> 
#> Slot "link_function":
#> [1] "log"
#> 
#> Slot "fixed_effects":
#> $cnt
#> [1] par   se    fixed
#> <0 rows> (or 0-length row.names)
#> 
#> 
#> 
#> Data
#> Simple feature collection with 404 features and 3 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: -95.23445 ymin: 36.11935 xmax: -89.2478 ymax: 40.47128
#> Geodetic CRS:  WGS 84
#> First 10 features:
#>     cnt year graph_idx                       geom
#> 422   1 2005        63 POINT (-95.23445 40.46577)
#> 417   7 2005        62 POINT (-95.03312 40.02546)
#> 402   5 2005        59 POINT (-94.66548 39.65398)
#> 415   7 2005        58 POINT (-94.50103 39.39702)
#> 416   3 2005        57 POINT (-94.14222 40.10026)
#> 392   3 2005        29   POINT (-94.1192 37.1404)
#> 420   4 2005        43 POINT (-94.10504 38.66985)
#> 384  11 2005        37  POINT (-93.9101 36.66086)
#> 391   7 2005        26 POINT (-93.85185 37.77059)
#> 397   2 2005        24 POINT (-93.84015 38.19498)
```

A 'staRVe_model_fit' object is an extension of a 'staRVe_model' object with some extra functionality providing tracing information (such as the parameter estimator covariance matrix, optimizer convergence, etc.) and model-based predictions.





# The staRVe model object

In this section we detail the various components of the 'staRVe_model' and 'staRVe_model_fit' classes.
The staRVe package makes use of S4 classes.
Users who are unfamiliar with S4 can think of an S4 class as a list, but elements of the list are accessed or modified using functions instead of the '$' or '[[' syntax.

## Parameter estimates


```r
convergence(bird_model)
#> [1] "relative convergence (4)"
```

The convergence message is only available after fitting a model.
Some of the convergence messages that indicate successful convergence of the optimization routine are

- "X-convergence (3)"
- "Relative convergence (4)"
- "Both X- and relative convergence (5)"

Some messages that indicate the optimization routine failed to converge are

- "Singular convergence"
- "false convergence"
- "function evaluation limit reached"

See '?nlminb' and the PORT routines documentation for more details.

The parameters hold the parameter values/estimates, the standard errors of the parameter estimates (for a fitted model), and whether the parameters are held fixed in the model.
These quantities are held in the 'par', 'se', and 'fixed' columns, respectively.
The spatial covariance function, response distribution, and link function used are also part of the parameter descriptions.
The parameters are split into groups according to the different conceptual parts of the model.

The spatial parameters describe the spatial covariance function for each response variable.
The staRVe package uses a Matern covariance function with the following parameters:

- **sd**: a scale parameter. Higher values correspond to spatial surfaces with larger peaks and lower valleys. Must be greater than 0.
- **range**: a range parameter. Typically interpreted as the distance by which two locations need to be separated to be approximately uncorrelated.
- **nu**: a smoothness parameter. Higher values correspond to smoother spatial surfaces. The smoothness parameter is only estimated when the covariance function is 'matern'. Must be greater than 0.



```r
covariance_function(bird_model)
#> [1] "exponential"
spatial_parameters(bird_model)
#> $cnt
#>               par          se fixed
#> sd     0.05213431 0.003913888 FALSE
#> range 80.00000000 0.000000000  TRUE
#> nu     0.50000000 0.000000000  TRUE
```

The time parameters describe the temporal structure of the random effects.
An autoregressive order 1 AR(1) model is used:

- **mu**: A mean parameter. The overall mean or the baseline level of the random effects.
- **ar1**: A correlation parameter. Higher values correspond to adjacent years being more highly correlated. Must be between -1 and +1.
- **sd**: A scale parameter. Higher values correspond to more year-to-year variation. Must be greater than 0.



```r
time_parameters(bird_model)
#> $cnt
#>           par         se fixed
#> mu  2.0066592 0.36396113 FALSE
#> ar1 0.9235859 0.03168324 FALSE
#> sd  0.1462888 0.07689308 FALSE
```

The response parameters describe e.g. the observation error, overdispersion, etc.
The specific parameters depend on the response distribution used and are described in section [Response distribution].


```r
response_distribution(bird_model)
#> [1] "poisson"
response_parameters(bird_model)
#> $cnt
#> [1] par   se    fixed
#> <0 rows> (or 0-length row.names)
```

The fixed effects describe the effects of covariates, as in a generalized linear model.
A description of how to include covariates in a staRVe analysis is given in section [Including covariates].


```r
fixed_effects(bird_model)
#> $cnt
#> [1] par   se    fixed
#> <0 rows> (or 0-length row.names)
```

You can extract all of the parameter values using the 'parameters' function.


```r
parameters(bird_model)
#> An object of class "staRVe_parameters"
#> Slot "covariance_function":
#> [1] "exponential"
#> 
#> Slot "spatial_parameters":
#> $cnt
#>               par          se fixed
#> sd     0.05213431 0.003913888 FALSE
#> range 80.00000000 0.000000000  TRUE
#> nu     0.50000000 0.000000000  TRUE
#> 
#> 
#> Slot "time_parameters":
#> $cnt
#>           par         se fixed
#> mu  2.0066592 0.36396113 FALSE
#> ar1 0.9235859 0.03168324 FALSE
#> sd  0.1462888 0.07689308 FALSE
#> 
#> 
#> Slot "response_distribution":
#> [1] "poisson"
#> 
#> Slot "response_parameters":
#> $cnt
#> [1] par   se    fixed
#> <0 rows> (or 0-length row.names)
#> 
#> 
#> Slot "link_function":
#> [1] "log"
#> 
#> Slot "fixed_effects":
#> $cnt
#> [1] par   se    fixed
#> <0 rows> (or 0-length row.names)
```


## Random effect predictions

The time effects are non-spatial random effects that describe the year-to-year change of the spatio-temporal random effects.
Higher predicted values of the time effects correspond to years with a higher yearly mean, but the time effects themselves are not interpretable as yearly means.
The main purpose of the time effects is to induce a correlation structure in the spatio-temporal random effects.


```r
time_effects(bird_model)
#> stars object with 2 dimensions and 2 attributes
#> attribute(s):
#>          Min.   1st Qu.    Median      Mean  3rd Qu.      Max.
#> w   1.8029625 1.9525085 1.9773921 2.0001284 2.083588 2.1469142
#> se  0.1354263 0.1829738 0.2140333 0.2091044 0.240983 0.2626549
#> dimension(s):
#>          from to offset delta refsys point values
#> year        1 10   2005     1     NA FALSE   NULL
#> variable    1  1     NA    NA     NA FALSE    cnt
```

The spatio-temporal random effects describe a spatial surface that varies from year to year.
The locations of the random effects act like the nodes in a mesh used in the R-INLA package, or basis functions used in a spline model.
The spatial surface at new locations are predicted using the values of these random effects.
The random effects are split into two groups.
The persistent graph random effects are placed at nodes that re-occur at the same location every year, and thus help
model the temporal structure of the model.
These random effects form a data cube, and we hold the random effect in a 'stars' object from the stars package.


```r
pg_re(bird_model)
#> stars object with 3 dimensions and 2 attributes
#> attribute(s):
#>           Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
#> w   0.05718306 1.2907399 1.8610265 1.8200176 2.3879027 3.6965085
#> se  0.13909556 0.2317798 0.3151045 0.3574355 0.4570195 0.9009079
#> dimension(s):
#>          from to offset delta refsys point
#> geom        1 63     NA    NA WGS 84  TRUE
#> year        1 10   2005     1     NA FALSE
#> variable    1  1     NA    NA     NA FALSE
#>                                                             values
#> geom     POINT (-89.24779 36.82526),...,POINT (-95.23445 40.46577)
#> year                                                          NULL
#> variable                                                       cnt
```

The transient graph random effects are placed at nodes at the location of each data point within a year (unless that
  location is already a persistent graph node location), and only in the year that the data point is observed.
These random effects are necessary to know the value of the spatio-temporal random effect value at each location.
Since the transient graph node locations do not form a data cube, we hold them in a 'long_stars' object (from the staRVe package).
The default options for the 'prepare_staRVe_model' function use all of the data locations as the persistent graph locations, so in our example there are no transient graph random effects.


```r
tg_re(bird_model)
#> An object of class "long_stars"
#> Slot "values":
#> stars object with 2 dimensions and 2 attributes
#> attribute(s):
#>     Min. 1st Qu. Median Mean 3rd Qu. Max. NA's
#> w      0       0      0    0       0    0    0
#> se    NA      NA     NA  NaN      NA   NA    1
#> dimension(s):
#>          from to offset delta refsys point values
#> i           1  1     NA    NA     NA FALSE [1,NA)
#> variable    1  1     NA    NA     NA FALSE    cnt
#> 
#> Slot "locations":
#> Simple feature collection with 0 features and 1 field
#> Bounding box:  xmin: NA ymin: NA xmax: NA ymax: NA
#> Geodetic CRS:  WGS 84
#> [1] year geom
#> <0 rows> (or 0-length row.names)
```

A list containing both sets of random effects can be extracted using the 'random_effects' function.


```r
random_effects(bird_model)
#> $pg_re
#> stars object with 3 dimensions and 2 attributes
#> attribute(s):
#>           Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
#> w   0.05718306 1.2907399 1.8610265 1.8200176 2.3879027 3.6965085
#> se  0.13909556 0.2317798 0.3151045 0.3574355 0.4570195 0.9009079
#> dimension(s):
#>          from to offset delta refsys point
#> geom        1 63     NA    NA WGS 84  TRUE
#> year        1 10   2005     1     NA FALSE
#> variable    1  1     NA    NA     NA FALSE
#>                                                             values
#> geom     POINT (-89.24779 36.82526),...,POINT (-95.23445 40.46577)
#> year                                                          NULL
#> variable                                                       cnt
#> 
#> $tg_re
#> An object of class "long_stars"
#> Slot "values":
#> stars object with 2 dimensions and 2 attributes
#> attribute(s):
#>     Min. 1st Qu. Median Mean 3rd Qu. Max. NA's
#> w      0       0      0    0       0    0    0
#> se    NA      NA     NA  NaN      NA   NA    1
#> dimension(s):
#>          from to offset delta refsys point values
#> i           1  1     NA    NA     NA FALSE [1,NA)
#> variable    1  1     NA    NA     NA FALSE    cnt
#> 
#> Slot "locations":
#> Simple feature collection with 0 features and 1 field
#> Bounding box:  xmin: NA ymin: NA xmax: NA ymax: NA
#> Geodetic CRS:  WGS 84
#> [1] year geom
#> <0 rows> (or 0-length row.names)
```

## Data

The data used in the model holds the data supplied to 'prepare_staRVe_model', and is held in a 'long_stars' object.
The 'predictions' slot contains a stars object for the random effect predictions (w), the response mean before applying the link function (linear), and the response mean after applying the link function (response).
Standard errors are also given for these predictions.
The 'locations' slot contains an sf object with columns for the response variable, any covariates, and the year column.
Note that the 'prepare_staRVe_model' function may sort the rows of the supplied data.


```r
data_predictions(bird_model)
#> An object of class "long_stars"
#> Slot "values":
#> stars object with 2 dimensions and 6 attributes
#> attribute(s):
#>                    Min.   1st Qu.    Median     Mean    3rd Qu.       Max.
#> w            0.05718306 1.4308494 1.9736939 1.947796  2.5315131  3.6965085
#> w_se         0.13909556 0.2097548 0.2528972 0.270597  0.3130637  0.5481214
#> linear       0.05718306 1.4308494 1.9736939 1.947796  2.5315131  3.6965085
#> linear_se    0.13909556 0.2097548 0.2528972 0.270597  0.3130637  0.5481214
#> response     1.05884963 4.1823690 7.1972278 9.420112 12.5725152 40.3063282
#> response_se  0.56629261 1.3245597 1.8694097 2.096810  2.6744114  5.8212710
#> dimension(s):
#>          from  to offset delta refsys point values
#> i           1 404      1     1     NA FALSE   NULL
#> variable    1   1     NA    NA     NA FALSE    cnt
#> 
#> Slot "locations":
#> Simple feature collection with 404 features and 3 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: -95.23445 ymin: 36.11935 xmax: -89.2478 ymax: 40.47128
#> Geodetic CRS:  WGS 84
#> First 10 features:
#>     cnt year graph_idx                       geom
#> 422   1 2005        63 POINT (-95.23445 40.46577)
#> 417   7 2005        62 POINT (-95.03312 40.02546)
#> 402   5 2005        59 POINT (-94.66548 39.65398)
#> 415   7 2005        58 POINT (-94.50103 39.39702)
#> 416   3 2005        57 POINT (-94.14222 40.10026)
#> 392   3 2005        29   POINT (-94.1192 37.1404)
#> 420   4 2005        43 POINT (-94.10504 38.66985)
#> 384  11 2005        37  POINT (-93.9101 36.66086)
#> 391   7 2005        26 POINT (-93.85185 37.77059)
#> 397   2 2005        24 POINT (-93.84015 38.19498)
```

The data held in the model can be easily accessed through the 'dat' function.


```r
dat(bird_model)
#> Simple feature collection with 404 features and 3 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: -95.23445 ymin: 36.11935 xmax: -89.2478 ymax: 40.47128
#> Geodetic CRS:  WGS 84
#> First 10 features:
#>     cnt year graph_idx                       geom
#> 422   1 2005        63 POINT (-95.23445 40.46577)
#> 417   7 2005        62 POINT (-95.03312 40.02546)
#> 402   5 2005        59 POINT (-94.66548 39.65398)
#> 415   7 2005        58 POINT (-94.50103 39.39702)
#> 416   3 2005        57 POINT (-94.14222 40.10026)
#> 392   3 2005        29   POINT (-94.1192 37.1404)
#> 420   4 2005        43 POINT (-94.10504 38.66985)
#> 384  11 2005        37  POINT (-93.9101 36.66086)
#> 391   7 2005        26 POINT (-93.85185 37.77059)
#> 397   2 2005        24 POINT (-93.84015 38.19498)
```

The rows of 'predictions' are in the same order as the rows of 'locations'.
We can add the random effect and response mean predictions to the data for plotting purposes.


```r
tmp<- cbind(
  do.call(cbind,values(data_predictions(bird_model))[,,1]),
  dat(bird_model)
)
#> Error in (function (classes, fdef, mtable) : unable to find an inherited method for function 'values' for signature '"long_stars"'
colnames(tmp)[1:6]<- c("w","w_se","linear","linear_se","response","response_se")
tmp
#> Simple feature collection with 25 features and 7 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: -95.1653 ymin: 36.1487 xmax: -89.41267 ymax: 40.43233
#> Geodetic CRS:  WGS 84
#> First 10 features:
#>            w      w_se    linear linear_se  response response_se year
#> 1  1.8955512 0.2865761 1.8955512 0.2865761  6.656217   1.9462823 2012
#> 2  2.2084346 0.3062870 2.2084346 0.3062870  9.101458   2.8522878 2012
#> 3  2.5666402 0.4376130 2.5666402 0.4376130 13.022000   5.9651888 2012
#> 4  2.9497865 0.3030088 2.9497865 0.3030088 19.101874   5.9194017 2012
#> 5  0.5778736 0.4711003 0.5778736 0.4711003  1.782245   0.8849758 2012
#> 6  2.0253046 0.3628623 2.0253046 0.3628623  7.578419   2.8389998 2013
#> 7  1.4405064 0.4669397 1.4405064 0.4669397  4.222834   2.0765089 2013
#> 8  1.3647776 0.3618621 1.3647776 0.3618621  3.914852   1.4622764 2013
#> 9  2.8740005 0.2918437 2.8740005 0.2918437 17.707716   5.2767796 2013
#> 10 3.2386208 0.2205022 3.2386208 0.2205022 25.498529   5.6904143 2013
#>                          geom
#> 1  POINT (-93.44969 37.48708)
#> 2   POINT (-92.76769 36.7374)
#> 3  POINT (-89.66307 36.49022)
#> 4  POINT (-89.41267 36.74711)
#> 5   POINT (-95.1653 40.43233)
#> 6  POINT (-91.23448 36.59283)
#> 7   POINT (-94.56619 36.1487)
#> 8  POINT (-92.09355 38.93433)
#> 9  POINT (-89.75907 36.99413)
#> 10 POINT (-89.79193 37.16898)
```



## Settings

The call to 'prepare_staRVe_model' can include various options that tweak the behaviour of the data pre-processing step.
Some of these options are stored as slots in model settings:

- **formula**: this is the formula supplied to 'prepare_staRVe_model'
- **n_neighbours**: the maximum number of parents that each node in the directed acyclic graph
- **distance_units**: units used for distance calculations. All distances in the model (for example max_distance, init_range, and graph distances) have these units.
- **max_distance**: the maximum distance that a location is allowed to be from nearest-neighbour parents


```r
settings(bird_model)
#> An object of class "staRVe_settings"
#> Slot "formula":
#> cnt ~ time(year)
#> 
#> Slot "n_neighbours":
#> [1] 15
#> 
#> Slot "distance_units":
#> [1] "km"
#> 
#> Slot "max_distance":
#> [1] Inf
```






# Modifying a staRVe model


Changing the covariance function also resets the spatial parameters, and updates the value of nu to reflect the specific covariance function as a special case of the Matern covariance.


```r
spatial_parameters(bird_model)
#> $cnt
#>               par          se fixed
#> sd     0.05213431 0.003913888 FALSE
#> range 80.00000000 0.000000000  TRUE
#> nu     0.50000000 0.000000000  TRUE

covariance_function(bird_model)<- "matern32"

spatial_parameters(bird_model)
#> $cnt
#>       par se fixed
#> sd    0.0  0 FALSE
#> range 0.0  0 FALSE
#> nu    1.5  0  TRUE
```

You can change the parameter values by accessing the relevant set of parameters, and changing the 'par' column of that data.frame.
Parameter values can be set to any numeric value, but values outside the valid range will be replaced with a default value when fitting, simulating from, or predicting using the model.
For example a 'sd' (standard deviation) parameter must be positive; if it is set to a negative value then a default of +1 will be used instead.
You can also change the 'se' and 'fixed' columns in the same way.


```r
spatial_parameters(bird_model)
#> $cnt
#>       par se fixed
#> sd    0.0  0 FALSE
#> range 0.0  0 FALSE
#> nu    1.5  0  TRUE
time_parameters(bird_model)
#> $cnt
#>           par         se fixed
#> mu  2.0066592 0.36396113 FALSE
#> ar1 0.9235859 0.03168324 FALSE
#> sd  0.1462888 0.07689308 FALSE

time_parameters(bird_model)$cnt[c("mu","ar1"),"par"]<- c(10,0.75)
spatial_parameters(bird_model)$cnt["range","par"]<- 80
spatial_parameters(bird_model)$cnt["range","fixed"]<- T

spatial_parameters(bird_model)
#> $cnt
#>        par se fixed
#> sd     0.0  0 FALSE
#> range 80.0  0  TRUE
#> nu     1.5  0  TRUE
time_parameters(bird_model)
#> $cnt
#>            par         se fixed
#> mu  10.0000000 0.36396113 FALSE
#> ar1  0.7500000 0.03168324 FALSE
#> sd   0.1462888 0.07689308 FALSE
```

Changing the response distribution will automatically update the response parameters, and will change the link function based on the valid range of the response mean for that distribution.
In the example above, the response distribution was changed from a Poisson distribution with no parameters and log link to a Gaussian distribution with a standard deviation parameter and identity link.


```r
response_distribution(bird_model)
#> [1] "poisson"
response_parameters(bird_model)
#> $cnt
#> [1] par   se    fixed
#> <0 rows> (or 0-length row.names)
link_function(bird_model)
#> [1] "log"

response_distribution(bird_model)<- "gaussian"

response_distribution(bird_model)
#> [1] "gaussian"
response_parameters(bird_model)
#> $cnt
#>    par se fixed
#> sd   0  0 FALSE
link_function(bird_model)
#> [1] "identity"
```

The link function can be changed to any implemented link function, even if it may give out of range predictions for the response distribution used in the model.
For example an identity link is allowed to be used with a Poisson response distribution even though an identity link may result in predictions with a negative mean.
Non-standard link functions should be used with caution, but are sometimes more desirable depending on the specific situation.


```r
link_function(bird_model)
#> [1] "identity"

link_function(bird_model)<- "logit"

link_function(bird_model)
#> [1] "logit"
```

You can modify the data in a 'staRVe_model' object by adding columns for new variables or amending data.
However because the data are pre-processed changing the number of rows will require the creation of a new model object using the 'prepare_staRVe_model' function.


```r
dat(bird_model)
#> Simple feature collection with 404 features and 3 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: -95.23445 ymin: 36.11935 xmax: -89.2478 ymax: 40.47128
#> Geodetic CRS:  WGS 84
#> First 10 features:
#>     cnt year graph_idx                       geom
#> 422   1 2005        63 POINT (-95.23445 40.46577)
#> 417   7 2005        62 POINT (-95.03312 40.02546)
#> 402   5 2005        59 POINT (-94.66548 39.65398)
#> 415   7 2005        58 POINT (-94.50103 39.39702)
#> 416   3 2005        57 POINT (-94.14222 40.10026)
#> 392   3 2005        29   POINT (-94.1192 37.1404)
#> 420   4 2005        43 POINT (-94.10504 38.66985)
#> 384  11 2005        37  POINT (-93.9101 36.66086)
#> 391   7 2005        26 POINT (-93.85185 37.77059)
#> 397   2 2005        24 POINT (-93.84015 38.19498)

dat(bird_model)$elev<- rnorm(nrow(dat(bird_model)))

dat(bird_model)
#> Simple feature collection with 404 features and 4 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: -95.23445 ymin: 36.11935 xmax: -89.2478 ymax: 40.47128
#> Geodetic CRS:  WGS 84
#> First 10 features:
#>     cnt year graph_idx                       geom       elev
#> 422   1 2005        63 POINT (-95.23445 40.46577) -1.3221890
#> 417   7 2005        62 POINT (-95.03312 40.02546)  0.9720445
#> 402   5 2005        59 POINT (-94.66548 39.65398)  0.7193741
#> 415   7 2005        58 POINT (-94.50103 39.39702)  0.8373455
#> 416   3 2005        57 POINT (-94.14222 40.10026)  0.6659404
#> 392   3 2005        29   POINT (-94.1192 37.1404) -0.6571608
#> 420   4 2005        43 POINT (-94.10504 38.66985) -0.9045444
#> 384  11 2005        37  POINT (-93.9101 36.66086) -0.5842451
#> 391   7 2005        26 POINT (-93.85185 37.77059)  1.3389180
#> 397   2 2005        24 POINT (-93.84015 38.19498)  1.1219474
```

The model formula for including covariates such as the newly created 'elev' variable will be explained later.
Any variables used in the new formula must be present in the data held in the staRVe_model object, so add them before changing the formula.
The fixed effects parameters will be automatically updated to reflect the new formula.


```r
formula(bird_model)
#> cnt ~ time(year)
fixed_effects(bird_model)
#> $cnt
#> [1] par   se    fixed
#> <0 rows> (or 0-length row.names)

formula(bird_model)<- cnt~elev+time(year)

formula(bird_model)
#> cnt ~ elev + time(year)
fixed_effects(bird_model)
#> $cnt
#>      par se fixed
#> elev   0 NA FALSE
```

The distance units used in calculations can be changed to any valid distance unit provided by the 'units' package.
Distances are standardized within the model so changing the distance units should not affect inference or predictions.


```r
spatial_parameters(bird_model)
#> $cnt
#>        par se fixed
#> sd     0.0  0 FALSE
#> range 80.0  0  TRUE
#> nu     1.5  0  TRUE
graph(bird_model)
#> $persistent_graph
#> 
#> [1] "A directed acyclic graph with 49 nodes, with an median in-degree of 15."
#> [1] "The average edge distance is 112.2km."
#> 
#> $transient_graph
#> Warning in mean.default(do.call(c, lapply(distances(object), c))): argument is
#> not numeric or logical: returning NA
#> 
#> [1] "A directed acyclic graph with 0 nodes, with an median in-degree of ."
#> [1] "The average edge distance is NAkm."
distance_units(bird_model)<- "ft"
#> Error in (function (classes, fdef, mtable) : unable to find an inherited method for function 'transient_graph' for signature '"staRVe_observations"'
spatial_parameters(bird_model)
#> $cnt
#>        par se fixed
#> sd     0.0  0 FALSE
#> range 80.0  0  TRUE
#> nu     1.5  0  TRUE
graph(bird_model)
#> $persistent_graph
#> 
#> [1] "A directed acyclic graph with 49 nodes, with an median in-degree of 15."
#> [1] "The average edge distance is 112.2km."
#> 
#> $transient_graph
#> Warning in mean.default(do.call(c, lapply(distances(object), c))): argument is
#> not numeric or logical: returning NA
#> 
#> [1] "A directed acyclic graph with 0 nodes, with an median in-degree of ."
#> [1] "The average edge distance is NAkm."
```








# Predictions

Once a staRVe model has been fit, you can then use the 'staRVe_predict' function to predict the mean value of the response variable at unobserved locations and years.
This allows us to fill in the gaps and produce smooth maps of the response variable and forecast those maps into the future (or the past).
Predictions can be made as individual locations or as a raster.

## Point predictions

We first randomly sample a small number of points for predictions each year, and store those points as an sf data.frame.
The prediction locations can be the same every year or they can be different, and the years of the predictions can be different from those in the original data.


```r
pred_points<- st_sample(
  st_as_sfc(st_bbox(bird_survey)),
  size = 25
)
pred_points<- st_sf(geom = pred_points,year=rep(2012:2016,each=5))
pred_points
#> Simple feature collection with 25 features and 1 field
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: -95.1653 ymin: 36.1487 xmax: -89.41267 ymax: 40.43233
#> Geodetic CRS:  WGS 84
#> First 10 features:
#>    year                       geom
#> 1  2012 POINT (-93.44969 37.48708)
#> 2  2012  POINT (-92.76769 36.7374)
#> 3  2012 POINT (-89.66307 36.49022)
#> 4  2012 POINT (-89.41267 36.74711)
#> 5  2012  POINT (-95.1653 40.43233)
#> 6  2013 POINT (-91.23448 36.59283)
#> 7  2013  POINT (-94.56619 36.1487)
#> 8  2013 POINT (-92.09355 38.93433)
#> 9  2013 POINT (-89.75907 36.99413)
#> 10 2013 POINT (-89.79193 37.16898)
```

The output is a staRVe_predictions object with two slots, a 'locations' slot containing an sf data.frame with any covariates used, the year, and the geometry, and a 'predictions' slot containing a stars object with attributes for:

- The spatio-temporal random effects **w**, and their standard errors **w_se**
- The response mean before applying the link function **linear**, and their standard errors **linear_se**
- the response mean after applying the link function **response**, and their standard errors **response_se**


```r
sf_pred<- staRVe_predict(
  bird_model,
  pred_points
)
sf_pred
#> An object of class "long_stars"
#> Slot "values":
#> stars object with 2 dimensions and 6 attributes
#> attribute(s):
#>                   Min.  1st Qu.    Median      Mean  3rd Qu.       Max.
#> w            0.5778736 1.398270 1.8673943 1.8267352 2.208435  3.2386208
#> w_se         0.2205022 0.306287 0.4561979 0.4713482 0.640092  0.7676484
#> linear       0.5778736 1.398270 1.8673943 1.8267352 2.208435  3.2386208
#> linear_se    0.2205022 0.306287 0.4561979 0.4713482 0.640092  0.7676484
#> response     1.7822446 4.048191 6.4714119 7.8895585 9.101458 25.4985292
#> response_se  0.8849758 1.946282 2.9582462 3.3045789 4.303532  6.1377236
#> dimension(s):
#>          from to offset delta refsys point values
#> i           1 25      1     1     NA FALSE   NULL
#> variable    1  1     NA    NA     NA FALSE    cnt
#> 
#> Slot "locations":
#> Simple feature collection with 25 features and 1 field
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: -95.1653 ymin: 36.1487 xmax: -89.41267 ymax: 40.43233
#> Geodetic CRS:  WGS 84
#> First 10 features:
#>    year                       geom
#> 1  2012 POINT (-93.44969 37.48708)
#> 2  2012  POINT (-92.76769 36.7374)
#> 3  2012 POINT (-89.66307 36.49022)
#> 4  2012 POINT (-89.41267 36.74711)
#> 5  2012  POINT (-95.1653 40.43233)
#> 6  2013 POINT (-91.23448 36.59283)
#> 7  2013  POINT (-94.56619 36.1487)
#> 8  2013 POINT (-92.09355 38.93433)
#> 9  2013 POINT (-89.75907 36.99413)
#> 10 2013 POINT (-89.79193 37.16898)
```

These predictions can be converted to a single sf data.frame fairly easily.


```r
tmp<- cbind(
  do.call(cbind,values(sf_pred)[,,1]),
  locations(sf_pred)
)
#> Error in (function (classes, fdef, mtable) : unable to find an inherited method for function 'values' for signature '"long_stars"'
colnames(tmp)[1:6]<- c("w","w_se","linear","linear_se","response","response_se")
tmp
#> Simple feature collection with 25 features and 7 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: -95.1653 ymin: 36.1487 xmax: -89.41267 ymax: 40.43233
#> Geodetic CRS:  WGS 84
#> First 10 features:
#>            w      w_se    linear linear_se  response response_se year
#> 1  1.8955512 0.2865761 1.8955512 0.2865761  6.656217   1.9462823 2012
#> 2  2.2084346 0.3062870 2.2084346 0.3062870  9.101458   2.8522878 2012
#> 3  2.5666402 0.4376130 2.5666402 0.4376130 13.022000   5.9651888 2012
#> 4  2.9497865 0.3030088 2.9497865 0.3030088 19.101874   5.9194017 2012
#> 5  0.5778736 0.4711003 0.5778736 0.4711003  1.782245   0.8849758 2012
#> 6  2.0253046 0.3628623 2.0253046 0.3628623  7.578419   2.8389998 2013
#> 7  1.4405064 0.4669397 1.4405064 0.4669397  4.222834   2.0765089 2013
#> 8  1.3647776 0.3618621 1.3647776 0.3618621  3.914852   1.4622764 2013
#> 9  2.8740005 0.2918437 2.8740005 0.2918437 17.707716   5.2767796 2013
#> 10 3.2386208 0.2205022 3.2386208 0.2205022 25.498529   5.6904143 2013
#>                          geom
#> 1  POINT (-93.44969 37.48708)
#> 2   POINT (-92.76769 36.7374)
#> 3  POINT (-89.66307 36.49022)
#> 4  POINT (-89.41267 36.74711)
#> 5   POINT (-95.1653 40.43233)
#> 6  POINT (-91.23448 36.59283)
#> 7   POINT (-94.56619 36.1487)
#> 8  POINT (-92.09355 38.93433)
#> 9  POINT (-89.75907 36.99413)
#> 10 POINT (-89.79193 37.16898)
```


## Raster predictions

To predict a raster for a smooth prediction surface you can supply a raster object from the 'raster' package.


```r
library(raster)
pred_raster<- raster(
  bird_survey,
  nrow = 5,
  ncol = 5
)
pred_raster
#> class      : RasterLayer 
#> dimensions : 5, 5, 25  (nrow, ncol, ncell)
#> resolution : 1.197331, 0.8703872  (x, y)
#> extent     : -95.23445, -89.24779, 36.11935, 40.47128  (xmin, xmax, ymin, ymax)
#> crs        : +proj=longlat +datum=WGS84 +no_defs
```

The 'staRVe_predict' function handles rasters by extracting the centroid of each raster cell and giving point predictions at those centroids.
The output is a stars object with predictions at each raster location and every year.


```r
staRVe_predict(
  bird_model,
  pred_raster
)
#> stars object with 4 dimensions and 6 attributes
#> attribute(s):
#>                   Min.   1st Qu.    Median     Mean   3rd Qu.       Max.
#> w            0.1615913 1.2324027 1.8309501 1.733903 2.2950947  3.3125145
#> w_se         0.2479856 0.3589519 0.4197394 0.412666 0.4536503  0.6910461
#> linear       0.1615913 1.2324027 1.8309501 1.733903 2.2950947  3.3125145
#> linear_se    0.2479856 0.3589519 0.4197394 0.412666 0.4536503  0.6910461
#> response     1.1753798 3.4294719 6.2401135 7.095404 9.9256294 27.4540749
#> response_se  0.6431997 1.5589103 2.5806664 2.784185 3.7161595  7.6653008
#> dimension(s):
#>          from to   offset     delta refsys point        values x/y
#> x           1  5 -95.2344   1.19733 WGS 84 FALSE          NULL [x]
#> y           1  5  40.4713 -0.870387 WGS 84 FALSE          NULL [y]
#> year        1 10     2005         1     NA    NA 2005,...,2014    
#> variable    1  1       NA        NA     NA    NA           cnt
```

If the supplied raster has values, then predictions will only be made at cells that are not NA.
See '?raster::mask' for details on creating raster with NAs.


```r
pred_raster[]<- 0
pred_raster[3,3]<- NA
pred_raster
#> class      : RasterLayer 
#> dimensions : 5, 5, 25  (nrow, ncol, ncell)
#> resolution : 1.197331, 0.8703872  (x, y)
#> extent     : -95.23445, -89.24779, 36.11935, 40.47128  (xmin, xmax, ymin, ymax)
#> crs        : +proj=longlat +datum=WGS84 +no_defs 
#> source     : memory
#> names      : layer 
#> values     : 0, 0  (min, max)
as.matrix(pred_raster)
#>      [,1] [,2] [,3] [,4] [,5]
#> [1,]    0    0    0    0    0
#> [2,]    0    0    0    0    0
#> [3,]    0    0   NA    0    0
#> [4,]    0    0    0    0    0
#> [5,]    0    0    0    0    0
pred_out<- staRVe_predict(
  bird_model,
  pred_raster
)
pred_out$response[,,1,1]
#>          [,1]     [,2]      [,3]      [,4]      [,5]
#> [1,] 4.615803 7.672447  6.713338  6.804606  7.755325
#> [2,] 3.424155 4.829670  5.403129 14.478708 11.001679
#> [3,] 3.325594 5.522541        NA 10.201815  7.046480
#> [4,] 4.897331 6.301414 13.208526  9.802879 10.857169
#> [5,] 7.078449 8.047967 10.407504 14.204704 11.183505
```

For raster predictions an additional 'time' option is available to specify which years to make predictions for, with the default behaviour being to predict every year between the earliest and latest year in the original dataset.


```r
staRVe_predict(
  bird_model,
  pred_raster,
  time = 2015:2019
)
#> stars object with 4 dimensions and 6 attributes
#> attribute(s):
#>                   Min.   1st Qu.    Median      Mean   3rd Qu.       Max. NA's
#> w            0.5569947 1.3213066 1.7767298 1.7402396 2.1608855  3.2150192    5
#> w_se         0.4142775 0.6395674 0.7250005 0.7219569 0.8223608  0.9714563    5
#> linear       0.5569947 1.3213066 1.7767298 1.7402396 2.1608855  3.2150192    5
#> linear_se    0.4142775 0.6395674 0.7250005 0.7219569 0.8223608  0.9714563    5
#> response     1.7454191 3.7520235 5.9106681 6.8113929 8.6829796 24.9037724    5
#> response_se  1.2097532 3.1630877 4.5958772 5.2097580 6.5890510 13.6785221    5
#> dimension(s):
#>          from to   offset     delta refsys point        values x/y
#> x           1  5 -95.2344   1.19733 WGS 84 FALSE          NULL [x]
#> y           1  5  40.4713 -0.870387 WGS 84 FALSE          NULL [y]
#> year        1  5     2015         1     NA    NA 2015,...,2019    
#> variable    1  1       NA        NA     NA    NA           cnt
```





# Simulation

Any 'staRVe_model' object can simulate new realizations of both the random effects and observations.
You can simulated from an already fitted model, or by first defining a new model from scratch.

Passing a fitted staRVe model to 'staRVe_simulate' simulates new time effects, new random effects, and new observations, using the parameter estimates (or whichever parameter values are current).
The output of 'staRVe_simulate' is itself a 'staRVe_model' object.
The parameter values are the same as those of the supplied model, however all standard errors have been replace with NA.
The time effects, random effects, and observations in the output are the simulated values.
No record of the previous values are stored.


```r
sim_model<- prepare_staRVe_model(
  cnt~time(year),
  bird_survey,
  distribution="poisson",
  fit=T
)
sim_model<- staRVe_simulate(sim_model)
sim_model
#> 
#> [1] "Simulated realization from model"
#> 
#> An object of class "staRVe_parameters"
#> Slot "covariance_function":
#> [1] "exponential"
#> 
#> Slot "spatial_parameters":
#> $cnt
#>                par se fixed
#> sd      0.04618762 NA FALSE
#> range 154.77282931 NA FALSE
#> nu      0.50000000 NA  TRUE
#> 
#> 
#> Slot "time_parameters":
#> $cnt
#>              par se fixed
#> mu  2.238769e+00 NA FALSE
#> ar1 9.334288e-01 NA FALSE
#> sd  3.439196e-05 NA FALSE
#> 
#> 
#> Slot "response_distribution":
#> [1] "poisson"
#> 
#> Slot "response_parameters":
#> $cnt
#> [1] par   se    fixed
#> <0 rows> (or 0-length row.names)
#> 
#> 
#> Slot "link_function":
#> [1] "log"
#> 
#> Slot "fixed_effects":
#> $cnt
#> [1] par   se    fixed
#> <0 rows> (or 0-length row.names)
#> 
#> 
#> 
#> Data
#> Simple feature collection with 404 features and 3 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: -95.23445 ymin: 36.11935 xmax: -89.2478 ymax: 40.47128
#> Geodetic CRS:  WGS 84
#> First 10 features:
#>     cnt year graph_idx                       geom
#> 422  26 2005        63 POINT (-95.23445 40.46577)
#> 417  29 2005        62 POINT (-95.03312 40.02546)
#> 402  10 2005        59 POINT (-94.66548 39.65398)
#> 415  25 2005        58 POINT (-94.50103 39.39702)
#> 416  19 2005        57 POINT (-94.14222 40.10026)
#> 392  33 2005        29   POINT (-94.1192 37.1404)
#> 420  17 2005        43 POINT (-94.10504 38.66985)
#> 384  24 2005        37  POINT (-93.9101 36.66086)
#> 391  16 2005        26 POINT (-93.85185 37.77059)
#> 397  22 2005        24 POINT (-93.84015 38.19498)
```

To simulate from a completely new model you first have to create a template sf data.frame.
The template data.frame needs to contain a column for the response variable, a column for any covariates desired, a column for the time variable, and a geometry column.
The values in the response variable column are irrelevant however the covariate values will be the ones used in the model, the time and geometry columns are also used to set up the spatio-temporal layout of the simulations.
We will use a sf data.frame with a 4x4 grid of points replicated over 5 years.


```r
sim_df<- st_as_sf(
  data.frame(
    y = 0,
    t = rep(1:5,each=16),
    ycoord = rep(1:4,4),
    xcoord = rep(1:4,each=4)
  ),
  coords = c("ycoord","xcoord")
)
sim_df
#> Simple feature collection with 80 features and 2 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: 1 ymin: 1 xmax: 4 ymax: 4
#> CRS:           NA
#> First 10 features:
#>    y t    geometry
#> 1  0 1 POINT (1 1)
#> 2  0 1 POINT (2 1)
#> 3  0 1 POINT (3 1)
#> 4  0 1 POINT (4 1)
#> 5  0 1 POINT (1 2)
#> 6  0 1 POINT (2 2)
#> 7  0 1 POINT (3 2)
#> 8  0 1 POINT (4 2)
#> 9  0 1 POINT (1 3)
#> 10 0 1 POINT (2 3)

sim_model<- prepare_staRVe_model(
  y~time(t),
  sim_df,
  distribution = "gaussian",
  fit = F
)
```

Once a staRVe model is created from the template data, the parameter values and other model options (such as the covariance function, link function, response distribution, etc.) need to be set to their desired value.
After doing so you can simulate new random effects and data from the model.


```r
time_parameters(sim_model)$y[c("mu","ar1","sd"),"par"]<- c(10,0.7,1)
spatial_parameters(sim_model)$y[c("sd","range"),"par"]<- c(2,0.5)
response_parameters(sim_model)$y["sd","par"]<- 0.5
sim_model<- staRVe_simulate(sim_model)
sim_model
#> 
#> [1] "Simulated realization from model"
#> 
#> An object of class "staRVe_parameters"
#> Slot "covariance_function":
#> [1] "exponential"
#> 
#> Slot "spatial_parameters":
#> $y
#>       par se fixed
#> sd    2.0 NA FALSE
#> range 0.5 NA FALSE
#> nu    0.5 NA  TRUE
#> 
#> 
#> Slot "time_parameters":
#> $y
#>      par se fixed
#> mu  10.0 NA FALSE
#> ar1  0.7 NA FALSE
#> sd   1.0 NA FALSE
#> 
#> 
#> Slot "response_distribution":
#> [1] "gaussian"
#> 
#> Slot "response_parameters":
#> $y
#>    par se fixed
#> sd 0.5 NA FALSE
#> 
#> 
#> Slot "link_function":
#> [1] "identity"
#> 
#> Slot "fixed_effects":
#> $y
#> [1] par   se    fixed
#> <0 rows> (or 0-length row.names)
#> 
#> 
#> 
#> Data
#> Simple feature collection with 80 features and 3 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: 1 ymin: 1 xmax: 4 ymax: 4
#> CRS:           NA
#> First 10 features:
#>           y t graph_idx    geometry
#> 1  16.04436 1         1 POINT (1 1)
#> 5  15.05160 1         5 POINT (1 2)
#> 9  13.92175 1         9 POINT (1 3)
#> 13 12.99514 1        13 POINT (1 4)
#> 2  11.75740 1         2 POINT (2 1)
#> 6  14.47301 1         6 POINT (2 2)
#> 10 14.46695 1        10 POINT (2 3)
#> 14 14.11784 1        14 POINT (2 4)
#> 3  14.61475 1         3 POINT (3 1)
#> 7  14.87963 1         7 POINT (3 2)
```



## Simulating random effects and observations

The default behaviour for simulations is to simulate new time effects, new random effects, and new data.
We show only the first few of each to show their difference before and after simulations.


```r
time_effects(sim_model)
#> stars object with 2 dimensions and 2 attributes
#> attribute(s):
#>        w           se          
#>  Min.   :10.38   Mode:logical  
#>  1st Qu.:10.54   NA's:5        
#>  Median :10.89                 
#>  Mean   :11.37                 
#>  3rd Qu.:11.21                 
#>  Max.   :13.85                 
#> dimension(s):
#>          from to offset delta refsys point values
#> t           1  5      1     1     NA FALSE   NULL
#> variable    1  1     NA    NA     NA FALSE      y
pg_re(sim_model)
#> stars object with 3 dimensions and 2 attributes
#> attribute(s):
#>        w            se          
#>  Min.   : 5.091   Mode:logical  
#>  1st Qu.: 9.011   NA's:80       
#>  Median :10.606                 
#>  Mean   :10.817                 
#>  3rd Qu.:13.032                 
#>  Max.   :15.994                 
#> dimension(s):
#>          from to offset delta refsys point                      values
#> geom        1 16     NA    NA     NA  TRUE POINT (1 1),...,POINT (4 4)
#> t           1  5      1     1     NA FALSE                        NULL
#> variable    1  1     NA    NA     NA FALSE                           y
head(dat(sim_model)$y)
#>          [,1]
#> [1,] 16.04436
#> [2,] 15.05160
#> [3,] 13.92175
#> [4,] 12.99514
#> [5,] 11.75740
#> [6,] 14.47301
sim_model<- staRVe_simulate(
  sim_model
)
time_effects(sim_model)
#> stars object with 2 dimensions and 2 attributes
#> attribute(s):
#>        w            se          
#>  Min.   : 9.264   Mode:logical  
#>  1st Qu.: 9.866   NA's:5        
#>  Median :11.395                 
#>  Mean   :10.814                 
#>  3rd Qu.:11.428                 
#>  Max.   :12.118                 
#> dimension(s):
#>          from to offset delta refsys point values
#> t           1  5      1     1     NA FALSE   NULL
#> variable    1  1     NA    NA     NA FALSE      y
pg_re(sim_model)
#> stars object with 3 dimensions and 2 attributes
#> attribute(s):
#>        w            se          
#>  Min.   : 6.092   Mode:logical  
#>  1st Qu.: 9.492   NA's:80       
#>  Median :10.686                 
#>  Mean   :10.877                 
#>  3rd Qu.:12.567                 
#>  Max.   :16.218                 
#> dimension(s):
#>          from to offset delta refsys point                      values
#> geom        1 16     NA    NA     NA  TRUE POINT (1 1),...,POINT (4 4)
#> t           1  5      1     1     NA FALSE                        NULL
#> variable    1  1     NA    NA     NA FALSE                           y
head(dat(sim_model)$y)
#>           [,1]
#> [1,] 10.004497
#> [2,] 13.613470
#> [3,]  9.172723
#> [4,] 13.881187
#> [5,] 12.545160
#> [6,]  9.634249
```


## Simulating only observations

Simulations of only new data, conditional on the existing time effects and random effects, can be made by giving the 'conditional=T' option.
Note that the time effects and random effects are the same before and after simulation, but that the response variable is different.


```r
time_effects(sim_model)
#> stars object with 2 dimensions and 2 attributes
#> attribute(s):
#>        w            se          
#>  Min.   : 9.264   Mode:logical  
#>  1st Qu.: 9.866   NA's:5        
#>  Median :11.395                 
#>  Mean   :10.814                 
#>  3rd Qu.:11.428                 
#>  Max.   :12.118                 
#> dimension(s):
#>          from to offset delta refsys point values
#> t           1  5      1     1     NA FALSE   NULL
#> variable    1  1     NA    NA     NA FALSE      y
pg_re(sim_model)
#> stars object with 3 dimensions and 2 attributes
#> attribute(s):
#>        w            se          
#>  Min.   : 6.092   Mode:logical  
#>  1st Qu.: 9.492   NA's:80       
#>  Median :10.686                 
#>  Mean   :10.877                 
#>  3rd Qu.:12.567                 
#>  Max.   :16.218                 
#> dimension(s):
#>          from to offset delta refsys point                      values
#> geom        1 16     NA    NA     NA  TRUE POINT (1 1),...,POINT (4 4)
#> t           1  5      1     1     NA FALSE                        NULL
#> variable    1  1     NA    NA     NA FALSE                           y
head(dat(sim_model)$y)
#>           [,1]
#> [1,] 10.004497
#> [2,] 13.613470
#> [3,]  9.172723
#> [4,] 13.881187
#> [5,] 12.545160
#> [6,]  9.634249
sim_model<- staRVe_simulate(
  sim_model,
  conditional=T
)
time_effects(sim_model)
#> stars object with 2 dimensions and 2 attributes
#> attribute(s):
#>        w            se          
#>  Min.   : 9.264   Mode:logical  
#>  1st Qu.: 9.866   NA's:5        
#>  Median :11.395                 
#>  Mean   :10.814                 
#>  3rd Qu.:11.428                 
#>  Max.   :12.118                 
#> dimension(s):
#>          from to offset delta refsys point values
#> t           1  5      1     1     NA FALSE   NULL
#> variable    1  1     NA    NA     NA FALSE      y
pg_re(sim_model)
#> stars object with 3 dimensions and 2 attributes
#> attribute(s):
#>        w            se          
#>  Min.   : 6.092   Mode:logical  
#>  1st Qu.: 9.492   NA's:80       
#>  Median :10.686                 
#>  Mean   :10.877                 
#>  3rd Qu.:12.567                 
#>  Max.   :16.218                 
#> dimension(s):
#>          from to offset delta refsys point                      values
#> geom        1 16     NA    NA     NA  TRUE POINT (1 1),...,POINT (4 4)
#> t           1  5      1     1     NA FALSE                        NULL
#> variable    1  1     NA    NA     NA FALSE                           y
head(dat(sim_model)$y)
#>           [,1]
#> [1,] 10.017073
#> [2,] 14.597501
#> [3,]  9.893089
#> [4,] 12.051603
#> [5,] 11.835742
#> [6,]  9.231888
```







# Including covariates

## Creating a model

First we add two dummy covariates 'elev' and 'temp' to our original data.


```r
bird_survey$elev<- rnorm(
  nrow(bird_survey)
)
bird_survey$temp<- rnorm(
  nrow(bird_survey)
)
```

Then we'll fit a model, using the formula to include the new covariates.
The estimates for the covariate effects are given in the fixed effects parameters.
Offset terms can be included by setting 'fixed=TRUE' for that covariate in the fixed effects parameters.
All covariates that are named in the model formula are also present in the data stored in the staRVe_model object.


```r
bird_model<- prepare_staRVe_model(
  cnt ~ elev+temp+time(year),
  bird_survey,
  distribution = "poisson",
  fit = T
)
fixed_effects(bird_model)
#> $cnt
#>               par         se fixed
#> elev  0.001391304 0.02556837 FALSE
#> temp -0.008900536 0.02606195 FALSE
dat(bird_model)
#> Simple feature collection with 404 features and 5 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: -95.23445 ymin: 36.11935 xmax: -89.2478 ymax: 40.47128
#> Geodetic CRS:  WGS 84
#> First 10 features:
#>            elev       temp cnt year graph_idx                       geom
#> 422  1.34828796  2.1010647   1 2005        63 POINT (-95.23445 40.46577)
#> 417  0.82879056  1.9879366   7 2005        62 POINT (-95.03312 40.02546)
#> 402 -0.06566962 -0.1125152   5 2005        59 POINT (-94.66548 39.65398)
#> 415 -0.78372086 -0.9049937   7 2005        58 POINT (-94.50103 39.39702)
#> 416  2.12633511  0.5939944   3 2005        57 POINT (-94.14222 40.10026)
#> 392  0.50074447 -1.9722455   3 2005        29   POINT (-94.1192 37.1404)
#> 420 -0.89223203  0.9132973   4 2005        43 POINT (-94.10504 38.66985)
#> 384 -0.17104232 -0.3689395  11 2005        37  POINT (-93.9101 36.66086)
#> 391  0.70427131 -0.5244365   7 2005        26 POINT (-93.85185 37.77059)
#> 397 -2.27217139  0.8688053   2 2005        24 POINT (-93.84015 38.19498)
```

More complex covariate effects such as interaction terms, transformations, and polynomial functions can be included in the model formula.


```r
bird_model<- prepare_staRVe_model(
  cnt ~ I(abs(temp))+poly(elev,2) + time(year),
  bird_survey,
  distribution = "poisson",
  fit = T
)
fixed_effects(bird_model)
#> $cnt
#>                        par        se fixed
#> I(abs(temp))   -0.04310055 0.0444570 FALSE
#> poly(elev, 2)1 -0.02728057 0.4892432 FALSE
#> poly(elev, 2)2 -0.42637251 0.5284338 FALSE
dat(bird_model)
#> Simple feature collection with 404 features and 5 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: -95.23445 ymin: 36.11935 xmax: -89.2478 ymax: 40.47128
#> Geodetic CRS:  WGS 84
#> First 10 features:
#>           temp        elev cnt year graph_idx                       geom
#> 422  2.1010647  1.34828796   1 2005        63 POINT (-95.23445 40.46577)
#> 417  1.9879366  0.82879056   7 2005        62 POINT (-95.03312 40.02546)
#> 402 -0.1125152 -0.06566962   5 2005        59 POINT (-94.66548 39.65398)
#> 415 -0.9049937 -0.78372086   7 2005        58 POINT (-94.50103 39.39702)
#> 416  0.5939944  2.12633511   3 2005        57 POINT (-94.14222 40.10026)
#> 392 -1.9722455  0.50074447   3 2005        29   POINT (-94.1192 37.1404)
#> 420  0.9132973 -0.89223203   4 2005        43 POINT (-94.10504 38.66985)
#> 384 -0.3689395 -0.17104232  11 2005        37  POINT (-93.9101 36.66086)
#> 391 -0.5244365  0.70427131   7 2005        26 POINT (-93.85185 37.77059)
#> 397  0.8688053 -2.27217139   2 2005        24 POINT (-93.84015 38.19498)
```


## Point predictions

We'll use the simpler covariate model for predictions.


```r
bird_model<- prepare_staRVe_model(
  cnt ~ elev+temp + time(year),
  bird_survey,
  distribution = "poisson",
  fit = T
)
```

We'll create an 'sf' object with our prediction points and years, along with the covariate values we want to use for predictions.


```r
pred_points<- st_sample(
  st_as_sfc(st_bbox(bird_survey)),
  size = 25
)
pred_points<- st_sf(geom = pred_points,year=rep(2012:2016,each=5))
pred_points$elev<- rnorm(nrow(pred_points))
pred_points$temp<- rnorm(nrow(pred_points))
pred_points
#> Simple feature collection with 25 features and 3 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: -94.70626 ymin: 36.32475 xmax: -89.3367 ymax: 40.27905
#> Geodetic CRS:  WGS 84
#> First 10 features:
#>    year                       geom       elev        temp
#> 1  2012  POINT (-93.20955 40.1978) -0.1568384 -0.43431142
#> 2  2012 POINT (-92.32139 36.32475)  0.1788332  0.79416674
#> 3  2012 POINT (-91.44953 37.92631)  0.7984350 -0.58376076
#> 4  2012 POINT (-91.46018 39.82648) -1.9367221 -0.42972340
#> 5  2012 POINT (-91.32337 40.27905)  1.6294998 -0.58097020
#> 6  2013 POINT (-89.92608 36.58008) -1.6585110  1.04889877
#> 7  2013  POINT (-93.16452 38.5783) -0.6631657 -2.01526012
#> 8  2013 POINT (-93.91487 36.43181)  0.4648332 -0.43874186
#> 9  2013 POINT (-91.21353 36.97279) -2.2180651 -0.09840643
#> 10 2013 POINT (-93.95435 38.32576) -2.1743246  1.00846581
```

The output is the same as predictions without covariates, but the covariates used are also included in the resulting 'long_stars' object.


```r
staRVe_predict(
  bird_model,
  pred_points
)
#> An object of class "long_stars"
#> Slot "values":
#> stars object with 2 dimensions and 6 attributes
#> attribute(s):
#>                   Min.   1st Qu.    Median      Mean   3rd Qu.       Max.
#> w            0.1736100 1.4626038 1.6519147 1.7133580 2.2924910  2.8210557
#> w_se         0.2282538 0.4008931 0.5007249 0.5265086 0.6248978  0.9158901
#> linear       0.1772573 1.4607508 1.6564665 1.7143263 2.2987976  2.8111438
#> linear_se    0.2296221 0.4039551 0.5008448 0.5280909 0.6266136  0.9165831
#> response     1.1939383 4.3091935 5.2407596 6.8415394 9.9621971 16.6289282
#> response_se  0.7609315 1.9847516 2.9945640 3.7579913 5.4172427 10.2216384
#> dimension(s):
#>          from to offset delta refsys point values
#> i           1 25      1     1     NA FALSE   NULL
#> variable    1  1     NA    NA     NA FALSE    cnt
#> 
#> Slot "locations":
#> Simple feature collection with 25 features and 3 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: -94.70626 ymin: 36.32475 xmax: -89.3367 ymax: 40.27905
#> Geodetic CRS:  WGS 84
#> First 10 features:
#>    year                       geom       elev        temp
#> 1  2012  POINT (-93.20955 40.1978) -0.1568384 -0.43431142
#> 2  2012 POINT (-92.32139 36.32475)  0.1788332  0.79416674
#> 3  2012 POINT (-91.44953 37.92631)  0.7984350 -0.58376076
#> 4  2012 POINT (-91.46018 39.82648) -1.9367221 -0.42972340
#> 5  2012 POINT (-91.32337 40.27905)  1.6294998 -0.58097020
#> 6  2013 POINT (-89.92608 36.58008) -1.6585110  1.04889877
#> 7  2013  POINT (-93.16452 38.5783) -0.6631657 -2.01526012
#> 8  2013 POINT (-93.91487 36.43181)  0.4648332 -0.43874186
#> 9  2013 POINT (-91.21353 36.97279) -2.2180651 -0.09840643
#> 10 2013 POINT (-93.95435 38.32576) -2.1743246  1.00846581
```




## Raster predictions


Covariates for raster predictions need to be supplied in a specific format: a list with a named element for each covariate.
The elements need to have the same name as the covariate.
Each covariate element needs to be a raster with the same geometry (dimensions, resolution, extent, coordinate reference system) as the raster template for the prediction locations.
Each layer of the covariate raster must correspond to a single year and be named "T####" where #### is replaced with the year.
The leading "T" in each layer name is necessary, and needs to specifically be a capitol "T".
For example, the layer "T2005" gives the covariate values for the year 2005.
Extra years of covariate values can be supplied, the 'staRVe_predict' function will only use the years for which predictions are made.


```r
pred_raster<- raster(
  bird_survey,
  nrow = 5,
  ncol = 5
)
raster_elev<- stack(lapply(min(bird_survey$year):2019,function(year) {
  band<- pred_raster
  band[]<- rnorm(ncell(band))
  names(band)<- paste0("T",year)
  return(band)
}))
raster_temp<- stack(lapply(min(bird_survey$year):2019,function(year) {
  band<- pred_raster
  band[]<- rnorm(ncell(band))
  names(band)<- paste0("T",year)
  return(band)
}))
pred_covar<- list(
  elev = raster_elev,
  temp = raster_temp
)
pred_covar
#> $elev
#> class      : RasterStack 
#> dimensions : 5, 5, 25, 15  (nrow, ncol, ncell, nlayers)
#> resolution : 1.197331, 0.8703872  (x, y)
#> extent     : -95.23445, -89.24779, 36.11935, 40.47128  (xmin, xmax, ymin, ymax)
#> crs        : +proj=longlat +datum=WGS84 +no_defs 
#> names      :     T2005,     T2006,     T2007,     T2008,     T2009,     T2010,     T2011,     T2012,     T2013,     T2014,     T2015,     T2016,     T2017,     T2018,     T2019 
#> min values : -1.036892, -3.418857, -2.062440, -1.518286, -1.957272, -2.600349, -1.742927, -2.254533, -1.757465, -1.430715, -2.662935, -1.714059, -1.912300, -2.004042, -2.211060 
#> max values :  1.574167,  1.537536,  1.605621,  1.845269,  1.354448,  1.440349,  1.297540,  1.640590,  2.197493,  1.855871,  2.438909,  1.426925,  2.286333,  2.742359,  2.219493 
#> 
#> 
#> $temp
#> class      : RasterStack 
#> dimensions : 5, 5, 25, 15  (nrow, ncol, ncell, nlayers)
#> resolution : 1.197331, 0.8703872  (x, y)
#> extent     : -95.23445, -89.24779, 36.11935, 40.47128  (xmin, xmax, ymin, ymax)
#> crs        : +proj=longlat +datum=WGS84 +no_defs 
#> names      :     T2005,     T2006,     T2007,     T2008,     T2009,     T2010,     T2011,     T2012,     T2013,     T2014,     T2015,     T2016,     T2017,     T2018,     T2019 
#> min values : -2.030086, -2.113791, -2.222009, -2.118209, -2.085452, -2.822138, -3.701192, -1.136959, -2.303146, -2.639094, -1.620791, -2.298241, -1.350512, -1.750296, -2.093928 
#> max values :  1.490701,  2.165628,  1.378064,  2.040302,  1.729857,  1.938088,  1.379020,  2.884803,  2.630402,  1.742325,  1.767252,  1.460482,  2.572266,  2.863586,  1.666899
```

For raster predictions, covariates are supplied to 'staRVe_predict' by giving the covariate raster list for the covariates is supplied as the third argument.
The output is the same as raster predictions without covariates, but the resulting stars raster for each year has  additional layer containing the covariate values.


```r
staRVe_predict(
  bird_model,
  pred_raster,
  pred_covar,
  time = min(bird_survey$year):2019
)
#> stars object with 4 dimensions and 8 attributes
#> attribute(s):
#>                     Min.    1st Qu.      Median        Mean   3rd Qu.      Max.
#> w            -0.04625461  1.2150404  1.83080041  1.73781301 2.2882786  3.328640
#> w_se          0.23293327  0.3808917  0.45557341  0.53669572 0.6393080  1.176374
#> linear       -0.04422721  1.2143137  1.83665872  1.73802573 2.2918081  3.340366
#> linear_se     0.23417380  0.3827674  0.45749807  0.53814965 0.6400083  1.177985
#> response      0.95673656  3.3680949  6.27553511  7.13943350 9.8929124 28.229454
#> response_se   0.60713613  1.9500360  3.27284145  3.79992058 4.9988906 15.111822
#> elev         -3.41885710 -0.5791440  0.01681079 -0.01760247 0.6390919  2.742359
#> temp         -3.70119214 -0.7568049 -0.01412138 -0.02665122 0.6404161  2.884803
#> dimension(s):
#>          from to   offset     delta refsys point        values x/y
#> x           1  5 -95.2344   1.19733 WGS 84 FALSE          NULL [x]
#> y           1  5  40.4713 -0.870387 WGS 84 FALSE          NULL [y]
#> year        1 15     2005         1     NA    NA 2005,...,2019    
#> variable    1  1       NA        NA     NA    NA           cnt
```






# Options

## Formula syntax

A model formula specifies the response variable, the covariate effects, the temporal structure, and the spatial structure.
Put together a model formula should have this general format:


```r
response ~ covariates + sample.size(...) + time(...) + space(...)
```

Some options to the individual terms in the above model formula can be specified, as described below.

- **covariates**: Covariate effects can be specified as they would be in a typical call to 'lm' or 'glm'. Can be omitted from the formula if no covariates effects are desired.
- **sample.size(...)**: Used only for specific response distributions, for example the binomial distribution. A single variable name should be supplied. Can be omitted from the formula, and sample sizes are assumed to be equal to 1 for all observations.
- **time(...,type=)**: The name of the column holding the time information should be given. For a purely spatial model, create a dummy 'time' column with entries all equal to the same value. Valid options for the type option are:
    - **independent**: Each year in the model is assumed to be independent. The 'ar1' time parameter is fixed at 0.
    - **ar1** (default): An autoregressive order 1 model is used. The 'ar1' time parameter is freely estimated.
    - **rw**: A random walk is used. The 'ar1' time parameter is fixed at 1.
- **space(...covariance=,nu=)**: The name of the covariance function should be given to the covariance argument. If using the 'matern' covariance function, supplying a value to the nu option fixes the smoothness parameter nu at that value. Can be omitted from the formula, in which case the default exponential covariance function will be used.


## Response distribution

The valid response distributions can be found with the 'get_staRVe_distributions' function:


```r
get_staRVe_distributions("distribution")
#>         distribution         distribution         distribution 
#>           "gaussian"            "poisson"  "negative binomial" 
#>         distribution         distribution         distribution 
#>          "bernoulli"              "gamma"          "lognormal" 
#>         distribution         distribution         distribution 
#>           "binomial" "atLeastOneBinomial"            "compois" 
#>         distribution 
#>            "tweedie"
```

- **gaussian**: Used for continuous data. Random effects and covariates determine the mean.
    - Parameters
        - **sd**: standard deviation of response variable.
    - Default link: identity
- **gamma**: Models strictly positive continuous data. Random effects and covariates determine the mean.
    - Parameters
        - **sd**: standard deviation of response variable.
    - Default link: log

- **lognormal**: Models strictly positive continuous data. Random effects and covariates determine the mean.
    - Parameters
        - **sd**: standard deviation of the log of response variable.
    - Default link: log

- **tweedie**: Models non-negative continuous data with a point mass at zero. Random effects and covariates determine the mean. The relationship between the mean and variance is given by $Var(Y) = \sigma^{2}\mu^{p}$.
    - Parameters
        - **dispersion**: The parameter $\sigma^{2}$ above.
        - **power**: The parameter $p$ above.
    - Default link: log

- **poisson**: Models non-negative integer data. Random effects and covariates determine the intensity/mean.
    - Parameters
        - N/A
    - Default link: log

- **negative binomial**: Model non-negative integer data with possible overdispersion. Random effects and covariates determine the mean.
    - Parameters
        - **overdispersion**: Values >1 correspond to overdispersion.
    - Default link: log

- **compois**: Models non-negative integer data with possible over- or underdispersion. Random effects and covariates determine the mean.
    - Parameters
        - **dispersion**: Values <1 correspond to underdispersion. Values >1 correspond to overdispersion
    - Default link: log

- **bernoulli**: Models binary data. Random effects and covariates determine the probability of success.
    - Parameters
        - N/A
    - Default link: logit

- **binomial**: Models the number of successes in *k* iid Bernoulli trials. Random effects and covariates determine the probability of success in a single trial. The number of trials *k* is specificed through the 'sample.size' term in the model formula.
    - Parameters
        - N/A
    - Default link: logit

- **atLeastOneBinomial**: Models the probability of observing at least one success in *k* iid Bernoulli trials. Random effects and covariates determine the probability of success in a single trial. The number of trials *k* is specified through the 'sample.size' term in the model formula.
    - Parameters
        - N/A
    - Default link: logit

## Link functions

The valid link functions can be found with the 'get_staRVe_distributions' function:


```r
get_staRVe_distributions("link")
#>       link       link       link 
#> "identity"      "log"    "logit"
```

- **identity**
    - Range (-$\infty$,$\infty$)

- **log**:
    - Range [0,$\infty$)

- **logit**:
    - Range [0,1]

## Spatial covariance function

All covariance functions currently available are special cases of the Matern covariance function.


```r
get_staRVe_distributions("covariance")
#>    covariance    covariance    covariance    covariance 
#> "exponential"    "gaussian"      "matern"    "matern32"
```

- **exponential**
    - Smoothness parameter nu = 0.5
- **matern32**
    - Smoothness parmaeter nu = 1.5
- **gaussian**
    - Limit of Matern covariance function as nu$\to\infty$
- **matern**
    - General covariance function with a freely estimated smoothness parameter nu. Evaluation is very slow compared to the named special cases.

## Holding parameters fixed

You can hold parameters fixed during model fitting.
Instead of being estimated the parameter value held in the staRVe model will be assumed "true".
We will hold the ar1 parameter fixed at 0, setting up each year in the model to be independent of the other years.
You can set as many parameters as you want to be held fixed, however the random effects cannot be fixed to particular values.
A model with all parameters held constant can still be fitted with the 'staRVe_fit' function, in which case the time effects and random effects will be estimated along with their standard errors.


```r
parameters(bird_model)
#> An object of class "staRVe_parameters"
#> Slot "covariance_function":
#> [1] "exponential"
#> 
#> Slot "spatial_parameters":
#> $cnt
#>               par          se fixed
#> sd     0.05213431 0.003913888 FALSE
#> range 80.00000000 0.000000000  TRUE
#> nu     0.50000000 0.000000000  TRUE
#> 
#> 
#> Slot "time_parameters":
#> $cnt
#>           par         se fixed
#> mu  2.0066592 0.36396113 FALSE
#> ar1 0.9235859 0.03168324 FALSE
#> sd  0.1462888 0.07689308 FALSE
#> 
#> 
#> Slot "response_distribution":
#> [1] "poisson"
#> 
#> Slot "response_parameters":
#> $cnt
#> [1] par   se    fixed
#> <0 rows> (or 0-length row.names)
#> 
#> 
#> Slot "link_function":
#> [1] "log"
#> 
#> Slot "fixed_effects":
#> $cnt
#> [1] par   se    fixed
#> <0 rows> (or 0-length row.names)

time_parameters(bird_model)$cnt["ar1","par"]<- 0
time_parameters(bird_model)$cnt["ar1","fixed"]<- T
bird_model<- staRVe_fit(bird_model,silent=T)

parameters(bird_model)
#> An object of class "staRVe_parameters"
#> Slot "covariance_function":
#> [1] "exponential"
#> 
#> Slot "spatial_parameters":
#> $cnt
#>              par          se fixed
#> sd     0.1050402 0.005070933 FALSE
#> range 80.0000000 0.000000000  TRUE
#> nu     0.5000000 0.000000000  TRUE
#> 
#> 
#> Slot "time_parameters":
#> $cnt
#>              par         se fixed
#> mu  2.019741e+00 0.08374696 FALSE
#> ar1 0.000000e+00 0.00000000  TRUE
#> sd  5.856547e-05 0.07227951 FALSE
#> 
#> 
#> Slot "response_distribution":
#> [1] "poisson"
#> 
#> Slot "response_parameters":
#> $cnt
#> [1] par   se    fixed
#> <0 rows> (or 0-length row.names)
#> 
#> 
#> Slot "link_function":
#> [1] "log"
#> 
#> Slot "fixed_effects":
#> $cnt
#> [1] par   se    fixed
#> <0 rows> (or 0-length row.names)
```
