all: staRVe.dll family.dll
	#
staRVe.dll: staRVe.cpp
	Rscript --vanilla -e "TMB::compile('staRVe.cpp',flags='-O3')"

family.dll: family.cpp
	Rscript --vanilla -e "TMB::compile('family.cpp',flags='-O3')"

clean:
	rm -rf *o
